General:
  Chats:
    # Range:
    #      -0 = All players see the message only in the world where it was sent.
    #      -1 = All players see the message in all worlds, but it was not sent to discord.
    #      -2 = All players see the message in all worlds, and sent to Discord.
    Local:  # Local chat
      DisplayName: 'local chat' # Chat name
      Enable: true  # Enable or disable local chat
      Range: 100  # Range within which players can see local chat messages
      Cooldown: -1  # Cooldown between messages (in seconds)
      Permission: "none" # Write 'none' if no permission required
      Format: '&b LOCAL &r{prefix}{player}{suffix}&8: {message}'  # Message format in local chat

    Global:  # Global chat
      DisplayName: 'global chat'  # Chat name
      Enable: true  # Enable or disable global chat
      Range: -2  # Range within which players can see global chat messages
      Cooldown: -1  # Cooldown between messages (in seconds)
      Symbol: '!'  # Symbol to send a message to global chat
      Permission: "none" # Write 'none' if no permission required
      Format: '&b GLOBAL &r{prefix}{player}{suffix}&8: {message}'  # Message format in global chat

    Staff:  # Staff chat
      DisplayName: 'staff chat'  # Chat name
      Enable: true  # Enable or disable staff chat
      Range: -2  # Range within which players can see staff chat messages
      Cooldown: -1  # Cooldown between messages (in seconds)
      Symbol: '#'  # Symbol to send a message to staff chat
      Permission: "ultimatechat.staffchat" # Write 'none' if no permission required
      Format: '&b STAFF &r{prefix}{player}{suffix}&8: {message}'  # Message format in staff chat

    Custom: # Custom chat
      DisplayName: 'custom-1'  # Chat name
      Enable: true # Enable or disable custom chat
      Range: -2  # Range within which players can see messages
      Cooldown: -1  # Cooldown between messages (in seconds)
      Symbol: '*' # Symbol to send a message
      Permission: "ultimatechat.customchat" # Write 'none' if no permission required
      Format: '&b CUSTOM &r{prefix}{player}{suffix}&8: {message}' # Message format

Discord:
  Enable: false # false | true
  Token: 'TOKEN'  # Your Discord bot token
  ChannelId: 'CHAT_ID'  # Discord channel ID for chat messages
  GuildId: 'id' # Discord server id
  ConsoleChannelId: '' # Discord channel ID for console
  BotStatus: 'suleks went to the drag store'
  ActivityType: 'playing' # playing: playing , listening: listening to , watching: watching .
  ActivityText: 'Farting in a bag' # activity text

  Link:
    Enable: true # link Discord account to Minecraft
    NoLink: "<gradient:#F2C6DE:#E43A96>Your account is not linked. To link, type /link {player} {code} in any Discord channel</gradient>"
    InvalidNickOrCode: "Invalid code or nickname. Provide a valid nickname and code"
    Successful: "Successfully linked account {DiscordName} to account {MinecraftName}"
    InvalidArgs: "Argument error in command!"

  UnLink:
    Enable: true
    NoLink: "You don't have a linked account, so nothing can be unlinked"
    Successful: "Successfully unlinked your account {DiscordName} from account {MinecraftName}!"

  Console: # discord console text-channel
    Blacklist-commands: #
      - "op"
      - "deop"

  Sync:  # Sync settings between discord and minecraft servers.
    Enable: true  # Enable or disable synchronization
    Minecraft-to-discord: true  # Send messages from Minecraft to Discord
    Discord-to-minecraft: true  # Send messages from Discord to Minecraft
    FromMinecraftToDiscord:
      Webhook:
        Name: '{PlayerName}' # placeholders can be written using {} or %, even PlaceholderAPI ones.
        Message: '{message}'
    FromDiscordToMinecraft: '&b DISCORD &r{user}&8: {message}' # Message format sent to Minecraft | {role} - user role,
    FromDiscordToMinecraft_Sound: 'ENTITY_ALLAY_DEATH' # Sound played for messages from Discord to Minecraft
    BanWords:
      - "nigger"
      - "naga"
      - "snot"

Server:
  Start:  # Server start message
    Enable: true  # Enable or disable server start message
    Message: 'Server started successfully!'  # Message displayed on server start

  Stop:  # Server stop message
    Enable: true  # Enable or disable server stop message
    Message: 'Server stopped!'  # Message displayed on server stop

Messages:
  AutoMessages:
    1:
      Text: "" # Text
      Interval: "" # Use: s, m, h, d

  WordsBlackList:
    - "Suka"
    - "Puka"
    - "Duka"

  DiscordFormat: 1 # you can use 1 or 2
  Join:  # Player join message
    Enable: true  # Enable or disable player join message
    Message: '&e{player} joined the game'  # Message displayed when a player joins
    Sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'  # Sound played on player join
    Discord:
      Text: ''
      Color: '' # HEX colors only

  Leave:  # Player leave message
    Enable: true  # Enable or disable player leave message
    Message: '&e{player} left the game'  # Message displayed when a player leaves
    Sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'  # Sound played on player leave
    Discord:
      Text: ''
      Color: '' # HEX colors only

  Death:  # Player death message
    Enable: true  # Enable or disable player death message
    Message: '&c{player} died from {cause}'  # Message displayed on player death
    Sound: 'ENTITY_BAT_DEATH'  # Sound played on player death
    Discord:
      Text: ''
      Color: '' # HEX colors only

Commands:
  Pm:  # Private message command
    Enable: true  # Enable or disable private messages
    Format: '&6[PM] &r{sender} -> {receiver}: {message}'  # Private message format
    FormatDiscord: '&6[PM from DS] &r{sender} -> {receiver}: {message}'  # Private message format
    Sound: ''  # Sound for private messages
  PmToDiscord:
    Enable: true
    Title: 'Message from player %sender%' # %sender% %player% %message%
    Description: '%message%' # %sender% %player% %message%
    Color: '#FF0000' # Hex color
    Footer: "Message sent via UltimateChat <3" # Footer