name: UltimateChat
version: '${project.version}'
main: sullexxx.ultimatechat.UltimateChat
api-version: '1.21'
depend: [LuckPerms, PlaceholderAPI]
commands:
  ultimatechat:
    aliases: [ "uc", "chat", "ultimate" ]
    permission: ultimatechat.command.main.use
  msg:
    usage: /msg <player> <message>
    aliases: [ pm, tell ]
  ball:
    description: "Magic 8-ball command"
  try:
    description: "Try to do something"
  flip:
    description: "Flip a coin"
  dice:
    description: "Roll a dice"