name: UltimateChat
version: '${project.version}'
main: sullexxx.ultimatechat.UltimateChat
api-version: '1.20'
commands:
  ultimatechat:
    aliases: [ "uc", "chat", "ultimate" ]
    permission: ultimatechat.command.main.use
